
networks:
  bondconnect-network:
    name: bondconnect-network
    driver: bridge

services:
  erc-20:
    build: ./tokenization-API/ERC20  # Path to build the ERC20 API image
    container_name: erc-20
    ports:
      - "3000:3000"
    working_dir: /app
    command: node dist/main.js
    networks:
      - bondconnect-network

  sa:
    build: ./tokenization-API/SA  # Path to build the SA API image
    container_name: sa
    ports:
      - "4000:4000"
    working_dir: /app
    command: node dist/main.js
    networks:
      - bondconnect-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - bondconnect-network

  bond-connect:
    build: ./webapp  # Path to build the BondConnect webapp image
    container_name: bond-connect
    ports:
      - "5000:5000"
    restart: always
    environment:
      - MONGO_URL=mongodb://mongo:27017/BondConnect
      - HOST_SMART_ACCOUNT=http://sa:4000
      - HOST_BRIDGE=http://erc-20:3000
    depends_on:
      - mongo
      - erc-20
      - sa
    networks:
      - bondconnect-network
    command: npm run dev

volumes:
  mongo_data: